config/routes.rb
# frozen_string_literal: true

#rubocop:disable all
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'superuser/add/adminuser', to: 'authentication#add_admin_user'
  post 'superuser/add/adminuser', to: 'authentication#add_user'
  get 'authentication/login', to: 'authentication#login'
  get '/auth/:provider/callback', to: 'authentication#create'
  get 'authentication/logout', to: 'authentication#logout'

  resources :profile, only: %i[index update]

  # Dashboard routes
  get 'dashboard/mytask'
  get 'dashboard/assigntask'
  get 'dashboard/adminpanel'
  get 'dashboard/hrpanel'
  put 'dashboard/mark_all_read'
  scope '/dashboard/hrpanel' do
    get 'generate_pdf', to: 'pdfs#generate_pdf'
  end
  scope '/dashboard/assigntask' do
    resources :tasks
    patch 'approve_task', to: 'tasks#approve'
  end

  # Admin Panel routes
  resources :admin, only: [] do
    collection do
      post 'add_user'
      patch 'change_role'
      patch 'send_to_hr'
      get 'search_user'
      resources :task_category, only: %i[create update destroy]
    end
  end

  # Task routes
  patch 'tasks/change_task_status'
  patch 'tasks/change_subtask_status'
  get 'tasks/apply_filters'
  post 'tasks/add_attachments'
  delete 'tasks/delete_attachments'
  get 'tasks/show'
  get 'tasks/search'

  # Exceptions
  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end
# rubocop:enable all

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# DashboardController class
class DashboardController < ApplicationController
  include ApplicationHelper
  include DashboardHelper

  before_action :current_user
  before_action :check_session, except: [:index]
  before_action :notifications, :all_notifications_type, except: [:index]

  def index
    redirect_to authentication_login_path unless session[:user_id].present?
    return unless session[:user_id].present?

    @user = User.find_by(employee_id: session[:user_id])
    redirect_to dashboard_mytask_path
  end

  def mytask
    @active_window = 'mytask'
    @assigned_mytasks = assigned_tasks
    @working_mytasks = working_tasks
    @completed_mytasks = completed_tasks
  end

  def assigntask
    @active_window = 'assigntask'
    @task_category = TaskCategory.all
    @all_users ||= User.all
    @all_assigned_tasks = Task.all_assigned_tasks(current_user.employee_id, params[:page])
  end

  def adminpanel
    @active_window = 'adminpanel'
    @total_user = User.count
    @all_verified_task = Task.approaved_tasks
    @all_users = User.page_wise_user(params[:page])
    @all_task_categories = TaskCategory.all
    @all_users_with_roles = User.all
  end

  def hrpanel
    @active_window = 'hrpanel'
    @all_sended_task = Task.snded_to_hr
  end

  def mark_all_read
    notifications.each do |item|
      item.read_status = true
      item.save
    end

    respond_to do |format|
      format.js { render locals: { notification: @notifications } }
    end
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

# DashboardHelper module
module DashboardHelper
  def assigned_tasks
    current_user.tasks.where(status: 0).page(params[:page]).per(3)
  end

  def working_tasks
    current_user.tasks.where(status: 1).page(params[:page]).per(3)
  end

  def completed_tasks
    current_user.tasks.where(status: 2).page(params[:page]).per(3)
  end
end

app/views/dashboard/adminpanel.html.erb
<div class="min-height-300 bg-primary position-absolute blue-bar" ></div>
<div class="container-fluid mt-5 position-relative">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-4 col-md-6 col-12">
          <div class="card mb-4 custom-card">
            <div class="card-body p-3 cursor-pointer" id="add-user-container">
              <div class="row">
                <div class="col-8">
                  <div class="numbers">
                    <p class="text-sm mb-0 text-uppercase font-weight-bold">
                      Users
                    </p>
                    <h5 class="font-weight-bolder" id="total-user-count">
                      <%= @total_user%>
                    </h5>
                    <p class="mb-0">Total Employee</p>
                  </div>
                </div>
                <div class="col-4 text-end d-flex align-items-center justify-content-center">
                  <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle"
                    id="add-user">
                    <i class="fas fa-duotone fa-user-plus user-add-btn"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-12">
          <div class="card mb-4 custom-card">
            <div class="card-body p-3">
              <div class="row">
                <div class="col-8">
                  <div class="numbers">
                    <p class="text-sm mb-0 text-uppercase font-weight-bold">
                      Pending Send to HR Department
                    </p>
                    <h5 class="font-weight-bolder" id="total-verified-task">
                      <%= @all_verified_task.count%>
                    </h5>
                    <p class="mb-0 strong">Total Approved Task</p>
                  </div>
                </div>
                <div class="col-4 text-end d-flex align-items-center justify-content-center">
                  <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle"
                    id="add-task">
                    <button class="btn btn-outline-primary" id="send-to-hr-btn">Send to HR</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-md-6 col-12">
        <div class="card mb-4 custom-card">
          <div class="card-body p-3 h-35">
            <h3 class="mb-3">List of Users</h3>
            <div class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search User" aria-label="Search"
                id="user-search" />
              <button class="btn btn-outline-success" type="submit" id="user-search-btn">
                Search
              </button>
            </div>
            <div class="table-responsive-sm table-responsive-md table-responsive-lg">
              <table class="table caption-top">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Role</th>
                    <th scope="col">Pending Task</th>
                    <th scope="col">Current Task</th>
                  </tr>
                </thead>
                <tbody id="employee_list">
                  <% @all_users.each do |item| %>
                    <tr>
                      <td>
                        <%=item.name+" "+item.surname%></td>
                  <td><%=item.roles%></td>
                  <td><%= item.pending_tasks_count %></td>
                  <td><%= item.working_tasks_count%></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            </div>
           <div class=" d-flex justify-content-center">
                          <%= paginate @all_users%>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-12">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-12" id="change-employee-details">
            <div class="card mb-4 custom-card hover h-10">
              <div class="card-body p-3 d-flex flex-row">
                <div class="row">
                  <div class="col-lg-6 col-md-6 col-12 d-flex align-items-center justify-content-center">
                    <h4>Change Employee Role here</h4>
                  </div>
                  <div class="col-lg-6 col-md-6 col-12 d-flex align-items-center justify-content-center">
                    <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle"
                      id="add-user">
                      <%= image_tag "edit.png" , {class: "rounded-circle" ,alt: "Hi" } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-12" id="add-task-categories">
            <div class="card mb-4 custom-card hover h-10" >
              <div class="card-body d-flex flex-row">
                <div class="row">
                  <div class="col-lg-6 col-md-6 col-12 d-flex align-items-center justify-content-center">
                    <h4>Add task Categories Here</h4>
                  </div>
                  <div class="col-lg-6 col-md-6 col-12 d-flex align-items-center justify-content-center">
                    <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle"
                      id="add-user">
                      <%= image_tag "addtask.png" , {class: "rounded-circle" ,alt: "Hi" } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<%= render partial:"shared/useradd" %>
  <%= render partial:"shared/changerole" %>
    <%= render partial:"shared/addTaskCategories" %>
      <%= render partial:"shared/sendToHr" %>

app/views/dashboard/assigntask.html.erb
<div class="min-height-300 bg-primary position-absolute blue-bar"></div>
<div class="container-fluid mt-5 position-relative">
  <div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-4 col-md-6 col-12 hover" id="assign-task-to-user">
          <div class="card mb-4 custom-card">
            <div class="card-body p-3">
              <div class="row">
                <div class="col-8">
                  <div class="numbers">
                    <p class="text-sm mb-0 text-uppercase font-weight-bold">
                      Assign Task
                    </p>
                    <p class="mb-0">To Employee</p>
                  </div>
                </div>
                <div class="col-4 text-end d-flex align-items-center justify-content-center">
                  <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle"
                    id="add-user">
                    <%= image_tag "task.png" , {class: "rounded-circle" ,alt: "Hi" } %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4 custom-card">
        <div class="card-body p-3 table-responsive-sm table-responsive-md table-responsive-lg">
          <h4 class="text-center">Already assiened tasks to the other users</h4>
          <table class="table caption-top">
            <thead>
              <tr>
                <th scope="col">Task Name</th>
                <th scope="col">Task Category</th>
                <th scope="col">Task Date</th>
                <th scope="col">Task Time</th>
                <th scope="col">Assigned to</th>
                <th scope="col">Importance</th>
                <th scope="col">Status</th>
                <th scope="col">Control</th>
              </tr>
            </thead>
            <tbody id="assigned_task_list">

              <% if @all_assigned_tasks.count==0 %>
                <tr id="no_record_row">
                  <td colspan="8" class="text-center">
                    No Records available
                  </td>
                </tr>
                <% end %>

                  <% @all_assigned_tasks.each do |task| %>
                    <tr>
                      <td>
                        <%=task.task_name%>
                      </td>
                      <td>
                        <%=task.task_category.task_name%>
                      </td>
                      <td>
                        <%=task.task_date.strftime("%A, %B %d, %Y") if task.task_date !=nil%>
                      </td>
                      <td>
                        <%=task.task_time.strftime("%H:%M %p") if task.task_date !=nil%>
                      </td>
                      <td>
                        <%= task.user.name+" "+task.user.surname %></td>
                  <td><%= task.task_importance %></td>
                  <td><%= task.status %></td>
                  <td>
                     <ul class=" list-inline m-0">
                          <li class="list-inline-item">
                            <%= link_to edit_task_path(task),class: "btn btn-success" do%>
                              <i class="fa fa-edit"></i>
                              <% end%>
                          </li>
                          <li class="list-inline-item">
                            <%= link_to task_path(task),data: {method: :delete, confirm: 'Are you sure?'
                              },class: "btn btn-danger" do%>
                              <i class="fa fa-trash"></i>
                              <% end%>
                          </li>
                          <li class="list-inline-item">
                            <%= link_to task_path(task,k: 1),:class=> "btn btn-primary" do %>
                              <i class="fa fa-eye"></i>
                              <% end %>
                          </li>
                          <% if(task.task_approval==false)%>
                            <li class="list-inline-item" id="approve_task_btn<%= task.id%>">
                              <button class="btn btn-primary approve_task_btn" data="<%= task.id%>">Approve</button>
                            </li>
                            <% else  %>
                              <li class="list-inline-item">
                              <button class="btn btn-outline-success approve_task_btn" disabled>Approved &#10003</button>
                              </li>
                            <% end %>
                              </ul>
                      </td>
                    </tr>
                    <% end %>
            </tbody>
          </table>
          <div class="d-flex justify-content-center">
            <%= paginate @all_assigned_tasks %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="task-add-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Assign Task</h5>
      </div>
      <div class="modal-body">

        <div class="form-group mt-3">
          <label for="task-name" class="form-label">Task Name</label>
          <input type="text" class="form-control" id="task-name" placeholder="Task Name" />
          <p id="task-name-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <label for="description" class="form-label">Task Descryption</label>
          <textarea class="form-control" id="description" rows="3" id="task-descryption"></textarea>
          <p id="task-des-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <label for="task-category">Task Category</label>
          <select id="task-category" class="form-select">
            <option selected>Choose...</option>
            <% @task_category.each do |category| %>
              <option value="<%=category.id%>">
                <%= category.task_name %>
              </option>
              <% end %>
          </select>
          <p id="task-category-error" class="text-danger"></p>
        </div>

        <div class="form-group mt-3">
          <ul id="sub-task-list">
          </ul>
          <input type="text" class="form-control" id="sub-task-input" placeholder="Sub Task" />
          <button id="add-subtask" class="btn btn-primary mt-2">Add Subtask</button>

        </div>
        <div class="form-group mt-3">
          <label for="task-date">Day task to be performed</label>
          <input type="date" class="form-control" id="task-date" min="<%= Date.tomorrow%>" name="task-date" onfocus="this.showPicker()"
            placeholder="Task Date" />
          <p id="task-date-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <label for="task-time">Time task to be performed</label>
          <input type="time" class="form-control" id="task-time" placeholder="Task Time" onfocus="this.showPicker()" />
          <p id="task-time-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <label for="assign-to">Assign To</label>
          <select id="assign-to" class="form-select">
            <option selected>Choose...</option>
            <% @all_users.each do |user| %>
              <option value="<%=user.id%>">
                <%= user.name+" "+user.surname %></option>
            <% end %>
          </select>
          <p id=" assign-to-error" class="text-danger">
                  </p>
        </div>
        <div class=" form-group mt-3">
          <label for="task-priority">Priority</label>
          <select id="task-priority" class="form-select">
            <option selected>Choose...</option>
            <option value="0">Low</option>
            <option value="1">Medium</option>
            <option value="2">High</option>
          </select>
          <p id="task-priority-error" class="text-danger"></p>
        </div>
        <div class=" form-group mt-3">
          <label class="form-check-label" for="repetation-cycle">
            Repeat Interval for task notification
          </label>
          <div class="form-check" id="repetation-cycle">
            <input class="form-check-input" type="radio" name="Interval" value="0">
            <label class="form-check-label" for="flexRadioDefault1">
              One Time
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="Interval" value="1">
            <label class="form-check-label" for="flexRadioDefault1">
              Daily
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="Interval" value="2">
            <label class="form-check-label" for="flexRadioDefault1">
              Weekly
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="Interval" value="3">
            <label class="form-check-label" for="flexRadioDefault1">
              Monthly
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="Interval" value="4">
            <label class="form-check-label" for="flexRadioDefault1">
              Quarterly
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="Interval" value="5">
            <label class="form-check-label" for="flexRadioDefault1">
              Half-yearly
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="Interval" value="6">
            <label class="form-check-label" for="flexRadioDefault1">
              Yearly
            </label>
          </div>
          <p id="repeat-interval-error" class="text-danger"></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="close-modal">
          Close
        </button>
        <button type="button" class="btn btn-primary" id="assign-task">
          Assign Task
        </button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/hrpanel.html.erb
<table class="table caption-top m-3">
            <thead>
              <tr>
                <th scope="col">Task Name</th>
                <th scope="col">Assigned to</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody id="verified_task_list">

              <% @all_sended_task.each do |task| %>
                <tr id="verified-task-<%= task.id%>">
                  <td>
                    <%=task.task_name%>
                  </td>
                  <td>
                    <%= task.user.name+" "+task.user.surname %></td>
                  <td>
                     <ul class=" list-inline m-0">
                      <li>
                      <%= link_to 'Download PDF', generate_pdf_path(id: task.id), class: 'btn btn-outline-success print-btn' %>
                      </li>
                      </ul>
                  </td>
                </tr>
                <% end %>
            </tbody>
</table>

app/views/dashboard/index.html.erb
<h1>Hello</h1>

app/views/dashboard/mark_all_read.js.erb
$('#notification-list').empty()
$('#notification-count').text("0")
$('#notification-list').append(`<li id="empty_notification">No Notification Yet </li>`)

app/views/dashboard/mytask.html.erb
<div class="min-height-300 bg-primary position-absolute blue-bar"></div>

<div class="container-fluid mt-3 position-relative">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4 custom-card p-3">
        <h3 class="text-center">My Task</h3>
        <div class="card-body  ">
          <ul class="nav nav-tabs mb-3" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="assigned-tab" data-bs-toggle="tab" data-bs-target="#assigned"
                type="button" role="tab" aria-controls="assigned" aria-selected="true">Assigned</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="working-tab" data-bs-toggle="tab" data-bs-target="#working" type="button"
                role="tab" aria-controls="working" aria-selected="false">Working</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="completed-tab" data-bs-toggle="tab" data-bs-target="#completed" type="button"
                role="tab" aria-controls="completed" aria-selected="false">Completed</button>
            </li>
          </ul>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="assigned" role="tabpanel" aria-labelledby="assigned-tab">
              <%= render partial:"shared/filterNav" ,:locals => {:status => "assigned"}%>
                <div>
                  <% if @assigned_mytasks.count == 0 %>
                    <h3 class="text-center no-assigned-task" id="my-assigned-empty-task">No Task Assigned</h3>
                  <% end  %>
                  <ul class="list-unstyled" id="my-assigned-task-list">
                    <% @assigned_mytasks.each do |task| %>
                      <%= render partial:"shared/taskItems", :locals => {:task => task}%>
                    <% end %>
                  </ul>
                  
                </div>
                <div class="d-flex justify-content-center">
                    <%= paginate @assigned_mytasks %>
                </div>
            </div>

            <div class="tab-pane fade" id="working" role="tabpanel" aria-labelledby="working-tab">
              <%= render partial:"shared/filterNav",:locals => {:status => "working"} %>
              <div>
                  <% if @working_mytasks.count == 0 %>
                    <h3 class="text-center no-assigned-task" id="my-working-empty-task">No Task Assigned</h3>
                   <% end  %>
                  <ul class="list-unstyled" id="my-working-task-list">
                    <% @working_mytasks.each do |task| %>
                      <%= render partial:"shared/taskItems", :locals => {:task => task}%>
                    <% end %>
                  </ul>
                 
                </div>
                <div class="d-flex justify-content-center">
                  <%= paginate @working_mytasks %>
                </div>
            </div>
            <div class="tab-pane fade" id="completed" role="tabpanel" aria-labelledby="completed-tab">
              <%= render partial:"shared/filterNav",:locals => {:status => "completed"} %>
              <div>
                  <% if @completed_mytasks.count == 0 %>
                    <h3 class="text-center no-assigned-task" id="my-completed-empty-task">No Task Assigned</h3>
                  <% end  %>
                  <ul class="list-unstyled" id="my-completed-task-list">
                    <% @completed_mytasks.each do |task| %>
                      <%= render partial:"shared/taskItems", :locals => {:task => task}%>
                    <% end %>
                  </ul>
                   
                </div>
                <div class="d-flex justify-content-center">
                  <%= paginate @completed_mytasks %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="task-add-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Assign Task</h5>
      </div>
      <div class="modal-body">
        <div class="form-group mt-3">
          <input type="text" class="form-control" id="task-name" placeholder="Task Name" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="close-modal">
          Close
        </button>
        <button type="button" class="btn btn-primary" id="assign-task">
          Assign Task
        </button>
      </div>
    </div>
  </div>
</div>