config/routes.rb
# frozen_string_literal: true

#rubocop:disable all
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'superuser/add/adminuser', to: 'authentication#add_admin_user'
  post 'superuser/add/adminuser', to: 'authentication#add_user'
  get 'authentication/login', to: 'authentication#login'
  get '/auth/:provider/callback', to: 'authentication#create'
  get 'authentication/logout', to: 'authentication#logout'

  resources :profile, only: %i[index update]

  # Dashboard routes
  get 'dashboard/mytask'
  get 'dashboard/assigntask'
  get 'dashboard/adminpanel'
  get 'dashboard/hrpanel'
  put 'dashboard/mark_all_read'
  scope '/dashboard/hrpanel' do
    get 'generate_pdf', to: 'pdfs#generate_pdf'
  end
  scope '/dashboard/assigntask' do
    resources :tasks
    patch 'approve_task', to: 'tasks#approve'
  end

  # Admin Panel routes
  resources :admin, only: [] do
    collection do
      post 'add_user'
      patch 'change_role'
      patch 'send_to_hr'
      get 'search_user'
      resources :task_category, only: %i[create update destroy]
    end
  end

  # Task routes
  patch 'tasks/change_task_status'
  patch 'tasks/change_subtask_status'
  get 'tasks/apply_filters'
  post 'tasks/add_attachments'
  delete 'tasks/delete_attachments'
  get 'tasks/show'
  get 'tasks/search'

  # Exceptions
  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end
# rubocop:enable all

app/models/task.rb
# frozen_string_literal: true

# Task Model
class Task < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  enum task_importance: {
    Low: 0,
    Medium: 1,
    High: 2
  }

  has_many :sub_tasks, dependent: :destroy
  has_many_attached :attachments

  belongs_to :user, optional: true
  belongs_to :task_category, foreign_key: 'task_category_id'

  after_create :create_uid

  validates :task_name, presence: true
  validates :task_category, presence: true
  validates :task_date, presence: true
  validates :task_time, presence: true
  validates :repeat_interval, presence: true
  validates :task_importance, presence: true
  validates :description, presence: true

  default_scope { order('DATE(task_date) ASC').order(task_importance: :desc) }
  scope :update_task_params, ->(id, update_params) { where(id:).update(update_params) }
  scope :find_authorized_task, lambda { |id, user_id|
                                 joins(:user).where(id:)
                                             .and(Task.where(assign_by: user_id)
                                             .or(Task.where(users: { employee_id: user_id })))
                               }
  scope :all_assigned_tasks, lambda { |employee_id, page_no|
                               where(assign_by: employee_id).order(:task_approval)
                                                            .page(page_no)
                                                            .per(10)
                             }
  scope :filter_user, ->(id) { where(user_id: id) }
  scope :filter_day, ->(day) { where('DATE(task_date) = ?', day) unless day.nil? }
  scope :filter_priority, ->(priority) { where(task_importance: priority) if priority != 3 }
  scope :filter_status, ->(status) { where(status: Task.statuses[status.titleize]) }
  scope :approaved_tasks, -> { where(task_approval: true).where(sended_to_hr: false) }
  scope :snded_to_hr, -> { where(sended_to_hr: true) }

  def self.index_data
    __elasticsearch__.create_index!
    __elasticsearch__.import force: true
  end

  settings do
    mappings dynamic: false do
      indexes :task_name, type: :text, analyzer: :english
      indexes :description, type: :text, analyzer: :english
      indexes :status, type: :integer
      indexes :user_id, type: :integer
      indexes :uid, type: :text
    end
  end

  def as_indexed_json(_options = {})
    {
      task_name:,
      description:,
      status: Task.statuses[status],
      user_id:,
      uid:
    }
  end

  def self.search_tasks(query, status, id)
    wildcards_query = query.split.map { |term| "*#{term}*" }.join(' ')
    response = search({ query: {
                        bool: {
                          must: [{ query_string: { query: wildcards_query, fields: %w[task_name description uid] } },
                                 { match: { user_id: id } }],
                          filter: { terms: { status: [status] } }
                        }
                      } })
    response.records
  end

  index_data

  def interval_of_notifications
    @interval_of_notification = {
      1 => 1.days,
      2 => 7.days,
      3 => 1.months,
      4 => 3.months,
      5 => 6.months,
      6 => 1.years
    }
  end

  def create_uid
    user_id = user.id
    self.uid = format('Task_%<timestamp>d%<user_id>03d%<id>03d', timestamp: Time.now.to_i, user_id:, id:)
    save
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# TasksController class
class TasksController < ApplicationController
  before_action :check_session, :current_user, :notifications, :all_notifications_type
  helper_method :change_task_status
  include ApplicationHelper
  include TasksHelper

  def create
    @task_user = User.find(task_params[:assign_to].to_i)
    date_time = parse_date_time(task_params[:task_date], task_params[:task_time])
    @task = create_task(date_time)
    post_task_creation_work
    respond_to { |format| format.js { render locals: { task: @task } } }
  end

  def show
    task_show_highlighter
    @task = Task.find_authorized_task(params[:id], session[:user_id])[0]
    @sub_tasks = @task&.sub_tasks
    return if @task.present?

    render file: Rails.public_path.join('401.html'), status: :unauthorized
    nil
  end

  def edit
    @active_window = 'assigntask'
    @task = Task.find(params[:id])
    return unless @task.assign_by != session[:user_id]

    render file: Rails.public_path.join('401.html'), status: :unauthorized
    nil
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to dashboard_assigntask_path
  end

  def update
    task = Task.find(params[:id])
    task.update(update_params)
    redirect_to dashboard_assigntask_path
  end

  def add_attachments
    task = Task.find(params[:id])
    task.attachments.attach(params[:task][:attachments])
    redirect_to edit_task_path(task)
  end

  def search
    make_search_params
    @records = Task.search_tasks(@query, @status, current_user.id)
    respond_to { |format| format.js { render locals: { records: @records, status: params[:search][:status] } } }
  end

  def change_task_status
    fn_st = update_task_status
    respond_to do |format|
      format.js { render locals: { final_status: fn_st[:status], task: fn_st[:tasks][0] } }
    end
  end

  def change_subtask_status
    sub_task = SubTask.update_subtask_params(sub_tasks_params[:id].to_i,
                                             { status: sub_tasks_params[:status].to_i })
    final_status = task_status_changed(sub_task[0].task_id)
    respond_to { |format| format.js { render locals: { final_status:, task: @task, sub_task: sub_task[0] } } }
  end

  def apply_filters
    identify = params[:filters][:identify]
    @mytasks = Task.filter_user(@user.id).filter_status(identify)
                   .filter_day(calculate_day).filter_priority(priority_generator)
    respond_to { |format| format.js { render locals: { identification: identify, task: @mytasks } } }
  end

  def approve
    @task = Task.find(params[:id].to_i)
    approave_task
    respond_to { |format| format.js { render locals: { task: @task } } }
  end

  private

  def task_params
    params.require(:task_data).permit(:task_name, :task_category, :task_date, :task_des, :task_time, :task_attachments,
                                      :notification_interval, :assign_to, :task_importance, sub_task: {})
  end

  def update_params
    params.require(:task).permit(:task_date, :task_time, :attachments)
  end

  def sub_tasks_params
    params.require(:subtask_data).permit(:id, :status, :attachments)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

# TasksHelper module
module TasksHelper
  def parse_date_time(date, time)
    DateTime.parse("#{date}T#{time}")
  end

  def create_task(date_time)
    @task_user.tasks.create(task_name: task_params[:task_name],
                            task_category: TaskCategory.find(task_params[:task_category]),
                            assign_by: @user.employee_id, task_importance: task_params[:task_importance].to_i,
                            task_date: date_time, task_time: date_time,
                            description: task_params[:task_des],
                            repeat_interval: task_params[:notification_interval].to_i, status: 0)
  end

  def create_sub_tasks(sub_tasks_params)
    sub_tasks_params.each do |_key, value|
      @task.sub_tasks.create(name: value, status: 0)
    end
  end

  def send_notification_for_task
    msg = "Task(#id: #{@task.uid}) Has been assigned to you by #{current_user.name} #{current_user.surname}"
    send_notification(@task_user.employee_id, msg)
    redirect_url = root_url.chop + dashboard_mytask_path
    TaskMailer.with(to: @task_user.email, task: @task, assign_user: current_user,
                    redirect: redirect_url).create.deliver_later
  end

  def post_task_creation_work
    create_sub_tasks(task_params[:sub_task]) if task_params[:sub_task].present?
    if @task.repeat_interval != 0
      date = Date.today + @task.interval_of_notifications[@task.repeat_interval]
      @task.next_notification_date = date
      @task.save
    end
    send_notification_for_task
  end

  def make_search_params
    @query = params[:search][:query]
    @status = all_task_status[params[:search][:status]]
  end

  def update_task_status
    task_id = params[:task_data][:id]
    remain_count = SubTask.pending_subtask_count(task_id)
    if params[:task_data][:status].to_i == 2 && remain_count.positive?
      { status: true, tasks: [] }
    else
      { tasks: Task.update_task_params(task_id, { status: params[:task_data][:status].to_i }), status: false }
    end
  end

  def task_status_changed(task_id)
    @task = Task.find(task_id)
    @task.updated_at > (Time.now - 1.minutes)
  end

  def day_param_generator
    params[:filters][:day].present? ? params[:filters][:day].to_i : 1
  end

  def priority_generator
    params[:filters][:priority].present? ? params[:filters][:priority].to_i : 3
  end

  def calculate_day
    day_param = params[:filters][:day].present? ? params[:filters][:day].to_i : 1
    case day_param
    when 0
      Date.tomorrow
    when 1
      Date.today
    when 2
      Date.yesterday
    end
  end

  def delete_attachments
    task = Task.find(params[:task_id])
    task.attachments.find(params[:blob_id]).destroy
    redirect_to edit_task_path(task)
  end

  def approave_task
    return unless @task.status_for_database == 2

    @task.task_approval = true
    @task.save
    TaskApprovalNotificationJob.perform_later(@task, current_user, @notifications_types[1])
  end
end

app/views/tasks/apply_filters.js.erb
$('#my-<%= identification%>-task-list').empty()
$('.no-assigned-task').remove()
<% if task.count == 0  %>
$('#my-<%= identification%>-task-list').append(`<h3>No such Task found</h3>`)
<% else  %>

  $('#my-<%= identification%>-task-list').empty() 
  $('#my-<%= identification%>-task-list').append(`<% task.each do |task| %>
                      <%= render partial:"shared/taskItems", :locals => {:task => task}%>
                    <% end %>`) 
<% end  %>

app/views/tasks/approve.js.erb
<% if task.status_for_database == 2  %>
$("#approve_task_btn<%= task.id%>").empty()
$("#approve_task_btn<%= task.id%>").append(` <button class="btn btn-outline-success approve_task_btn" disabled>Approved &#10003</button>`)
 show_toast("Task has been approved")
<% else  %>
  alert("Task is yet to complete")
<% end  %>

function show_toast(msg){
  var toastElList = [].slice.call(document.querySelectorAll('.toast'))
  var toastList = toastElList.map(function(toastEl) {
    $(toastEl).children()[1].innerHTML=msg
    return new bootstrap.Toast(toastEl)
  })
  toastList.forEach(toast => toast.show())
}

app/views/tasks/change_subtask_status.js.erb
$('#subtask-status-view-<%= sub_task.id%>').remove()

$('#subtask-status-container-<%= sub_task.id%>').append(`<p class="badge profile-text" id="subtask-status-view-<%= sub_task.id%>">
                    <%= sub_task.status%>
                    <span class="dot <%= sub_task.status.downcase%>"></span>`)

<% if final_status==true %>
$('#task-<%= task.id%>').remove();
$('#my-<%= task.status.downcase%>-empty-task').remove();
$('#my-<%= task.status.downcase%>-task-list').append(`<%= render partial:"shared/taskItems", :locals => {:task => task}%>`)
<% end  %>

app/views/tasks/change_task_status.js.erb
<% if final_status==true %>
alert("All subtask is not completed yet")
 <%# setTimeout(function() { %>
  window.location = '/dashboard/mytask';
  <%# }, 500);  %>
<% else  %>

$('#task-<%= task.id%>').remove();
$('#my-<%= task.status.downcase%>-empty-task').remove();

$('#my-<%= task.status.downcase%>-task-list').append(`<%= render partial:"shared/taskItems", :locals => {:task => task}%>`)

<% end %>

app/views/tasks/create.js.erb
<% if task %>
  $('#task-name').val('')
  $('#task-category').val('');
  $('#task-date').val('')
  $('#task-time').val('')
  $('#description').val('')
  $('#assign-to').val('')
  $('#task-priority').val('')
  $("#sub-task-list").empty();
<% end  %>
<% if Task.all_assigned_tasks(current_user.employee_id, 1).count == 1  %>
  $('#no_record_row').remove();
<% end %>
$('#close-modal').trigger('click')
$('#assigned_task_list').append(` <tr>
                  <td>
                    <%=task.task_name%>
                  </td>
                  <td>
                    <%=task.task_category.task_name%>
                  </td>
                  <td>
                    <%=task.task_date.strftime("%A, %B %d, %Y") if task.task_date !=nil%>
                  </td>
                  <td>
                    <%=task.task_date.strftime("%H:%M %p") if task.task_date !=nil%>
                  </td>
                  <td>
                    <%= task.user.name+" "+task.user.surname %></td>
                  <td><%= task.task_importance %></td>
                  <td>Assigned</td>
                  <td>
                     <ul class=" list-inline m-0">
                      <li class="list-inline-item">
                        <%= link_to edit_task_path(task),class: "btn btn-success" do%>
                          <i class="fa fa-edit"></i>
                          <% end%>
                      </li>
                      <li class="list-inline-item">
                        <%= link_to task_path(task),data: {method: :delete, confirm: 'Are you sure?'
                          },class: "btn btn-danger" do%>
                          <i class="fa fa-trash"></i>
                          <% end%>
                      </li>
                      <li class="list-inline-item">
                        <%= link_to task_path(task),:class=> "btn btn-primary" do %>
                          <i class="fa fa-eye"></i>
                          <% end %>
                      </li>
                       <li class="list-inline-item" id="approve_task_btn<%= task.id%>">
                              <button class="btn btn-primary approve_task_btn" data="<%= task.id%>">Approve</button>
                            </li>
                      </ul>
                  </td>
                </tr>`)

app/views/tasks/edit.html.erb
<div class="min-height-300 bg-primary position-absolute blue-bar"></div>
<div class="container-fluid mt-5 position-relative">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4 custom-card p-3 task-cards">
      <h3 class="text-center">Change Task Details Here</h3>
        <%= form_with model: @task, local: true ,url: task_path(@task) do |f| %>
          <div class="form-group mb-3">
           <label for="task-date">Day task to be performed </label>
          <%= f.date_field :task_date ,{class: "form-control",id: "task-date",min: Date.tomorrow,onfocus: "this.showPicker()"}%>
          </div>
          <div class="form-group mb-3">
          <label for="task-time">Time task to be performed </label>
          <%= f.time_field :task_time ,{class: "form-control",id: "task-time",onfocus: "this.showPicker()"}%>
          </div>
          <%= f.submit "Edit", class: "btn btn-primary m-auto",id: "submit_btn" %>
            
        <% end %>
       
      </div>
    </div>
  </div>
  <% if @task.attachments.present?  %>
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4 custom-card p-3 ">
      <h3 class="text-center">Attachments</h3>
      <div class="d-flex flex-row justify-content-center align-items-center">
          <% @task.attachments.each do |pic|  %>
          <% if pic.blob.content_type.include?("image")  %>
          <% timestamp = Time.now.strftime('%Y%m%d%H%M%S') %>
          <% filename = "image_#{timestamp}.jpg"   %>
          <div class="image-area">
            <%= link_to  url_for(pic.blob) , download: true  do %>
            <%= image_tag pic, {class: "m-2 p-2 attach-image",alt: "Hi"}%>
          <% end  %>
            <a class="remove-image d-inline" href="<%= tasks_delete_attachments_path(task_id: @task, blob_id: pic)%>" data-method="delete" data-confirm="Are you sure?">&#215;</a>
          </div>
          <% else  %>
          <div class="image-area">
              <%= link_to  url_for(pic.blob), download: true  do %>
              <%= image_tag 'file.png', {class: "m-2 p-2 attach-image",alt: "Hi"}%>
              <% end  %>
            <a class="remove-image d-inline" href="<%= tasks_delete_attachments_path(task_id: @task, blob_id: pic)%>" data-method="delete" data-confirm="Are you sure?">&#215;</a>
          </div>
          <% end  %>
      <% end %>
      </div>
          
      </div>
    </div>
  </div>
  <% end  %>
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4 custom-card p-3 task-cards">
      <h3 class="text-center">Add Attachments</h3>

       <%= form_with model: Task.new, local: true ,url: tasks_add_attachments_path(id: @task),id: "attachment_form" do |f| %>
          <div class="form-group mb-3">
          <%= f.file_field :attachments ,{class: "form-control",id: "upload_attachments"}%>
          </div>
          <input type="submit" name="commit" value="Add Attachments" class="btn btn-primary m-auto" id="submit_btn">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/search.js.erb
$('#my-<%= status%>-task-list').empty()
<% if records.count == 0  %>
$('#my-<%= status%>-task-list').append(`<h3>No such Task found</h3>`)
<% end  %>
<% records.each do |rc|  %>

$('#my-<%= status%>-task-list').append(`<%= render partial:"shared/taskItems", :locals => {:task => rc}%>`)
<% end  %>

app/views/tasks/show.html.erb
<div class="min-height-300 bg-primary position-absolute blue-bar"></div>
<div class="container-fluid mt-5 position-relative">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4 custom-card p-3 task-cards">
        <h2>Task Details</h2>
        <div class="horizontal-line"></div>
        <div class="card-body p-3 w-50">
          <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Task Name
              <p class="badge profile-text">
                <%= @task.task_name%>
              </p>
            </li>
            <li class=" list-group-item d-flex justify-content-between align-items-center">
              Category
              <p class="badge profile-text">
                <%= @task.task_category.task_name%>
              </p>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Assigned To
              <p class="badge profile-text">
                <%= @task.user.name+" "+@task.user.surname%>
                  </p>
                </li>
                <li class=" list-group-item d-flex justify-content-between align-items-center">
                  Scheduled Date
                  <p class="badge profile-text">
                    <%= @task.task_date.tomorrow? ? "Tommorw" : @task.task_date.strftime("%A, %B %d, %Y")%>
                  </p>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Scheduled Time
              <p class="badge profile-text">
                <%= @task.task_date.strftime("%H:%M %p")%>
              </p>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Current Status
              <p class="badge profile-text">
                <%= @task.status%>
                  <span class="dot <%= @task.status.downcase%>"></span>
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% if @sub_tasks.count>0  %>
  <div class="container d-flex align-items-center flex-column">
    <h3 class="mt-2">Subtasks</h3>
    <div class="horizontal-line-small"></div>
    <div class="container mt-3 justify-content-center sub-task-container">
      <ul>
      <% @sub_tasks.each do |subtask| %>
        <li class="list-group-item sub-tasks-border d-flex justify-content-between align-items-center">
          <%= subtask.name %>
          <p class="badge profile-text">
            <%= subtask.status%>
              <span class="dot <%= subtask.status.downcase%>"></span>
          </p>
        </li>  
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

<% if @task.attachments.present?  %>
  <div class="card card-body d-flex align-items-center">
  <h5 class="text-center">Attachment</h5>
  <div class="d-flex flex-row justify-content-center align-items-center">
      <% @task.attachments.each do |pic|  %>
          <% if pic.blob.content_type.include?("image")  %>
          <% timestamp = Time.now.strftime('%Y%m%d%H%M%S') %>
          <% filename = "image_#{timestamp}.jpg"   %>
          <%= link_to  url_for(pic.blob) , download: true  do %>
          <%= image_tag pic, {class: "m-2 p-2 attach-image",alt: "Hi"}%>
          <% end  %>
          <% else  %>
         <%= link_to  url_for(pic.blob), download: true  do %>
          <%= image_tag 'file.png', {class: "m-2 p-2 attach-image",alt: "Hi"}%>
          <% end  %>
          <% end  %>
      <% end %>
  </div>
</div>
<% end  %>