config/routes.rb
# frozen_string_literal: true

#rubocop:disable all
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'superuser/add/adminuser', to: 'authentication#add_admin_user'
  post 'superuser/add/adminuser', to: 'authentication#add_user'
  get 'authentication/login', to: 'authentication#login'
  get '/auth/:provider/callback', to: 'authentication#create'
  get 'authentication/logout', to: 'authentication#logout'

  resources :profile, only: %i[index update]

  # Dashboard routes
  get 'dashboard/mytask'
  get 'dashboard/assigntask'
  get 'dashboard/adminpanel'
  get 'dashboard/hrpanel'
  put 'dashboard/mark_all_read'
  scope '/dashboard/hrpanel' do
    get 'generate_pdf', to: 'pdfs#generate_pdf'
  end
  scope '/dashboard/assigntask' do
    resources :tasks
    patch 'approve_task', to: 'tasks#approve'
  end

  # Admin Panel routes
  resources :admin, only: [] do
    collection do
      post 'add_user'
      patch 'change_role'
      patch 'send_to_hr'
      get 'search_user'
      resources :task_category, only: %i[create update destroy]
    end
  end

  # Task routes
  patch 'tasks/change_task_status'
  patch 'tasks/change_subtask_status'
  get 'tasks/apply_filters'
  post 'tasks/add_attachments'
  delete 'tasks/delete_attachments'
  get 'tasks/show'
  get 'tasks/search'

  # Exceptions
  match '*unmatched', to: 'application#not_found', layout: false, via: :all, constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end
# rubocop:enable all

app/views/shared/_addTaskCategories.html.erb
<div
  class="modal fade"
  id="addTaskCategoriesModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Task Categories</h5>
      </div>
      <div class="modal-body">
        <ul class="list-group" id="task-list">
          <% @all_task_categories.each do |item| %>
          <li class="list-group-item d-flex flex-column justify-content-between align-items-center" id="task-<%=item.id%>">
            <div class="d-flex justify-content-between align-items-center w-100" id="category-list-<%= item.id%>">
              <p class="align-items-center mb-0"><%= item.task_name %></p>
              <div>
              <i class="fa fa-edit btn btn-success edit-task-category" value="<%= item.id%>"></i>
              <i class="fa fa-trash btn btn-danger del-task-category" value="<%= item.id%>"></i>
              </div>
            </div>
            <div class="input-group mt-3 d-none" id="category-edit-container-<%= item.id%>">
              <input type="text" class="form-control"  aria-label="Recipient's username" aria-describedby="button-addon2" id="category-edit-input-<%= item.id%>" value="<%= item.task_name%>">
              <button class="btn btn-outline-success category-edit-save" type="button" value="<%= item.id%>">Save</button>
            </div>
          </li>
          <% end %>
        </ul>

        <div class="form-group mt-3">
          <input
            type="text"
            class="form-control"
            id="input-category"
            placeholder="Task Category Name" />
             <p id="task-category-error" class="text-danger"></p>
        </div>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          id="close-modal-task-category">
          Close
        </button>
        <button type="button" class="btn btn-primary" id="add-task-caregory">
          Add Category
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_changerole.html.erb
<div
  class="modal fade"
  id="exampleModal2"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div
    class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"
    role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Change Roles</h5>
      </div>
      <div class="modal-body">
        <div class="card">
          <table class="table caption-top">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Role</th>
                <th scope="col">Chnage Role</th>
              </tr>
            </thead>
            <tbody id="employee_list_2">
              <% @all_users_with_roles.each do |item| %>
              <tr id="<%= item.id%>">
                <td><%=item.name+" "+item.surname%></td>
                <td id="roles-<%=item.id%>"><%=item.roles%></td>
                <td>
                  <div>
                    <% if item.Employee? %>
                    <button type="button" id="make-hrd-<%=item.id%>" class="btn btn-outline-primary make-hr" value="<%= item.id%>" >
                      Make HRD
                    </button>
                    <% end %>
                    <% if item.HRD? || item.Employee? %>
                    <button type="button" id="make-admin-<%=item.id%>" class="btn btn-outline-primary make-admin" value="<%= item.id%>">
                      Make Admin
                    </button>
                    <% end %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          id="close-modal-2">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_filterNav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li>
          <select class="form-select day-filter" aria-labelledby="navbarDropdown" id="<%= status%>-day-filter" data="<%= status%>">
            <option value="3">Day</option>
            <option value="0">Tomorrow</option>
            <option value="1">Today</option>
            <option value="2">Yesterday</option>
          </select>
        </li>
        <%# <li><input type="date" class="form-control" placeholder="Task Date" /></li> %>
        <li>
          <select class="form-select priority-filter" aria-labelledby="navbarDropdown" id="<%= status%>-priority-filter" data="<%= status%>">
            <option selected value="3">Priority</option>
            <option value="0">Low</option>
            <option value="1">Medium</option>
            <option value="2">High</option>
          </select>
        </li>
      </ul>
      <div class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="<%= status%>-search-bar">
        <button class="btn btn-outline-success search-btn" type="submit" data="<%= status%>">Search</button>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_flash.html.erb
<div class="container flash" id="flash-container">
  <% flash.each do |type, msg| %>
  <div class="alert alert-<%=type%> text-center" id="flash" role="alert">
    <%= msg %>
  </div>
  <script>
    function remove_flash(){
      $(document).ready(function(){
        setTimeout(function(){
        
          $('#flash').fadeOut();
        }, 3000);
      })
    }
    remove_flash()
  </script>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar2 navbar-expand-lg bg-body-tertiary navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand navbar-brand-color" href=<%=root_path%> id="app-name" style="font-size:1.5rem;">Task
      Management System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "My Task" , dashboard_mytask_path,class: "nav-link link-dark #{" active" if
            (@active_window=="mytask" )}",id:"my-task-li" %>
        </li>
        <li class="nav-item">
          <%= link_to "Assign Task" , dashboard_assigntask_path,class: "nav-link link-dark #{" active" if
            (@active_window=="assigntask" )}" ,id:"assign-li"%>
        </li>
        <% if (session[:role]==2)%>
          <li class="nav-item">
            <%= link_to "Admin Panel" , dashboard_adminpanel_path,class: "nav-link link-dark #{" active" if
              (@active_window=="adminpanel" )}" ,id:"admin-li"%>
          </li>
          <%elsif (session[:role]==1)%>
            <li class="nav-item">
              <%= link_to "HR Control" , dashboard_hrpanel_path,class: "nav-link link-dark #{" active" if
                (@active_window=="hrpanel" )}",id:"hr-li" %>
            </li>
            <%end%>
              <li>
                <hr class="dropdown-divider text-white">
              </li>
              <li class="nav-item">
                <%= link_to "Profile" ,profile_index_path,class:"nav-link text-white" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign out" ,authentication_logout_path,class:"nav-link text-white" %>
              </li>
      </ul>
    </div>
    <% if session[:user_id] %>
      <div class="dropdown dropstart">
        <a class="btn btn-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
          data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-bell"></i>
          <span id="notification-count" class="badge rounded-pill badge-notification bg-warning"
            data-count="<%= @notifications.count%>">
            <%= @notifications.count%>
          </span>

        </a>
        <ul class="dropdown-menu nav-notification p-2" id="notification-list"
          aria-labelledby="dropdownMenuButton1">
           <button class="btn btn-warning mark-read <%=@notifications.count.positive? ? "" : " d-none"%>" value=""
                id="mark-as-read" >Mark all as read</button>
            <li class=" <%=@notifications.count.positive? ?  " d-none" : "" %>" id="empty_notification">No Notification Yet</li>
          <% @notifications.each do |item| %>
            <a href="<%= @notifications_types[item.notification_type]%>" style="text-decoration: none; color: black;">
            <li>
              <div class="card mt-2">
                <div class="card-body">
                  <p class="card-text">
                    <%= item.message %>
                  </p>
                </div>
              </div>
            </li>
            </a>
            <% end %>
        </ul>
      </div>
      <% end %>

  </div>
</nav>

app/views/shared/_sendToHr.html.erb
<div
  class="modal fade"
  id="sendTaskModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="sendTaskModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="sendTaskModalLabel">Send to HR Department</h5>
      </div>
      <div class="modal-body">
        <table class="table caption-top">
            <thead>
              <tr>
                <th scope="col">Task Name</th>
                <th scope="col">Task Category</th>
                <th scope="col">Task Date</th>
                <th scope="col">Task Time</th>
                <th scope="col">Assigned to</th>
                <th scope="col">Importance</th>
                <th scope="col">Status</th>
                <th scope="col">Control</th>
              </tr>
            </thead>
            <tbody id="verified_task_list">

               <% if @all_verified_task.count == 0  %>
                <tr>
                <td colspan="8" class="text-center">
                  No Approved Task available
                </td>
                </tr>
              <% end  %>

              <% @all_verified_task.each do |task| %>
                <tr id="verified-task-<%= task.id%>">
                  <td>
                    <%=task.task_name%>
                  </td>
                  <td>
                    <%=task.task_category.task_name%>
                  </td>
                  <td>
                    <%=task.task_date.strftime("%A, %B %d, %Y") if task.task_date !=nil%>
                  </td>
                  <td>
                    <%=task.task_date.strftime("%H:%M %p") if task.task_date !=nil%>
                  </td>
                  <td>
                    <%= task.user.name+" "+task.user.surname %></td>
                  <td><%= task.task_importance %></td>
                  <td>Assigned</td>
                  <td>
                     <ul class=" list-inline m-0">
                      <li>
                      <i class="btn btn-success hr-send-btn" data="<%= task.id%>"> Send</i>
                      </li>
                      </ul>
                  </td>
                </tr>
                <% end %>
            </tbody>
          </table>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          id="close-modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="flex-column min-vh-100 p-3 nav-color side-responsive" style="width: 280px; z-index: 100">
  <ul class="nav nav-pills flex-column mb-auto" id="side-list" user_id="<%= session[:user_id]%>">
    <li class="nav-item">
      <%= link_to "My Task" , dashboard_mytask_path,class: "nav-link link-dark
      #{" active" if (@active_window=="mytask" )}",id:"my-task-li" %>
    </li>
    <li class="nav-item">
      <%= link_to "Assign Task" , dashboard_assigntask_path,class: "nav-link
      link-dark #{" active" if (@active_window=="assigntask" )}" ,id:"assign-li"%>
    </li>
    <% if (session[:role]==2)%>
      <li class="nav-item">
        <%= link_to "Admin Panel" , dashboard_adminpanel_path,class: "nav-link
      link-dark #{" active" if (@active_window=="adminpanel" )}" ,id:"admin-li"%>
      </li>
      <%elsif (session[:role]==1)%>
        <li class="nav-item">
          <%= link_to "HR Control" , dashboard_hrpanel_path,class: "nav-link
      link-dark #{" active" if (@active_window=="hrpanel" )}",id:"hr-li" %>
        </li>
        <%end%>
  </ul>
  <hr />
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
      data-bs-toggle="dropdown" aria-expanded="false">
      <%if(@user.image.present?)%>
        <%= image_tag @user.image, {class: "rounded-circle carausal-img" ,style: "width:80px; height:80px" }%>
          <%else%>
            <%= image_tag "user.png" , {class: "rounded-circle carausal-img
      me-2" ,style: "width:80px; height:80px" }%>
              <%end%>
                <strong>
                  <%=@user.name.to_s+" "+@user.surname.to_s%></strong>
    </a>

    <ul
      class=" dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1" style="">
                    <%= link_to "Profile" ,profile_index_path,class:"nav-link text-white" %>
                      <li>
                        <hr class="dropdown-divider" />
                      </li>
                      <%= link_to "Sign out" ,authentication_logout_path,class:"nav-link text-white" %>
                        </ul>
  </div>
</div>

app/views/shared/_taskItems.html.erb
 <li id="task-<%= task.id%>">
  <div class="card mb-4 custom-card2 p-4">
    <p>#id: <%= task.uid %></p>
    <h4><%= task.task_name %></h4>
    <div class="card-body task-item-card" style="padding: 0.5rem;" data-bs-toggle="collapse"
            data-bs-target="#sub-task-view-<%=task.id%>" aria-expanded="false" aria-controls="sub-task-view-<%=task.id%>">
      <div class="row">
        <div class="col-7">
          <h6 style="display: inline;">Assigned By : </h6>
          <p style="display: inline; color: blueviolet;"><%= User.find_by(employee_id: task.assign_by).name %></p>
        </div>
        <div class="col-4">
          <h6 style="display: inline;">Priority</h6>
          <p style="display: inline; color: blueviolet;"><%= task.task_importance%> 
          <span>
          <%= image_tag task.task_importance+".png" , {class: "rounded-circle" ,alt: "Hi", style: "height:20px;width:20px" } %>
          </span>
        </div>
        <div class="col-1">
          <%= link_to tasks_show_path(id:task,k: 2),:class=> "btn " do %>
            <i class="fa fa-eye"></i>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-7">
          <h6 style="display: inline;">Due Date : </h6>
          <p style="display: inline; color: blueviolet;"><%= task.task_date.strftime("%A, %B %d, %Y") %></p>
        </div>
        <div class="col-4">
          <h6 style="display: inline;">Due Time : </h6>
          <p style="display: inline; color: blueviolet;"><%= task.task_date.strftime("%H:%M %p") %></p>

        </div>

        <div class="col-1">
          <button class=" drop-down-btn " id="drop-down-<%=task.id%>" type="button" data-bs-toggle="collapse"
            data-bs-target="#sub-task-view-<%=task.id%>" aria-expanded="false" aria-controls="sub-task-view-<%=task.id%>"> 
           <i class="fa fa-caret-down"></i> Expand
          </button>
          <button class="btn"></button>
        </div>
      </div>
      <div class="collapse" id="sub-task-view-<%=task.id%>">
        <div class="card card-body">
        <h5 class="text-center">Description of Task</h5>
        <p><%= task.description %></p>
        </div>
        <% if task.sub_tasks.all.count>0  %>
        <div class="card card-body">
          <h4 class="text-center">Subtasks</h4>
          <ul>
          <% task.sub_tasks.all.each do |subtask|  %>
              <li class="list-group-item d-flex justify-content-between align-items-center"
                style="border-left: 2px solid black;">
                  <div class="row w-100">
                  <div class="col-6 d-flex align-items-center">
                    <%= subtask.name %>
                  </div>
                  <div class="col-4 d-flex align-items-center" id="subtask-status-container-<%= subtask.id%>">
                    <p class="badge profile-text" id="subtask-status-view-<%= subtask.id%>">
                    <%= subtask.status%>
                    <span class="dot <%= subtask.status.downcase%>"></span>
                  </p>
                  </div>
                  <div class="col-2 d-flex align-items-center">
                    <select class="form-select subtask-status-change" id="<%= subtask.id%>" aria-labelledby="navbarDropdown">
                      <option <%= "selected" if subtask.Assigned? %> value="0">Assigned</option>
                      <option <%= "selected" if subtask.Working? %> value="1">Working</option>
                      <option <%= "selected" if subtask.Completed? %> value="2">Completed</option>
                    </select>
                  </div>
                  </div>
              </li>
              <% end %>
          </ul>
        </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-end">
        <select class="form-select task-status-change" id="<%= task.id%>" aria-labelledby="navbarDropdown" style="width: auto;">
          <option <%= "selected" if task.Assigned? %> value="0">Assigned</option>
          <option <%= "selected" if task.Working? %> value="1">Working</option>
          <option <%= "selected" if task.Completed? %> value="2">Completed</option>
        </select>
      </div>
    </div>
  </div>
</li>

app/views/shared/_useradd.html.erb
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add User</h5>
      </div>
      <div class="modal-body">
        <div class="form-group mt-3">
          <input
            type="text"
            class="form-control"
            id="input-fname"
            placeholder="First name" />
            <p id="first-name-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <input
            type="text"
            class="form-control"
            id="input-lname"
            placeholder="Last name" />
            <p id="last-name-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <input
            type="email"
            class="form-control"
            id="input-email"
            placeholder="Email" />
            <p id="email-error" class="text-danger"></p>
        </div>
        <div class="form-group mt-3">
          <label for="input-roles">Roles</label>
          <select id="input-roles" class="form-control">
            <option selected>Choose...</option>
            <option value="0">Employee</option>
            <option value="1">HRD</option>
            <option value="2">Admin</option>
          </select>
          <p id="roles-error" class="text-danger"></p>
        </div>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          id="close-modal">
          Close
        </button>
        <button type="button" class="btn btn-primary" id="add-user-to-db">
          Add User
        </button>
      </div>
    </div>
  </div>
</div>